- :url: http://kamery.hydronet.cz/lysa/photo/l2_now.jpg
  :interval: 150 # it is every 20 minutes
  :desc: karkonosze_lysa_hora2
  :resize: true
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/lysa/photo/l5_now.jpg
  :interval: 150 # it is every 20 minutes
  :desc: karkonosze_lysa_hora5
  :resize: true
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/korenov/photo/korenov_960x1280_now.jpg
  :interval: 250
  :desc: karkonosze_korenove
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/jerabkovna/photo/jerabkovna_1600x1200_now.jpg
  :interval: 180
  :desc: karkonosze_jerabkovna_Jizerka
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/bukovec/photo/bukovec_1600x1200_now.jpg
  :interval: 180
  :desc: karkonosze_bukovec_Osada_Jizerka
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/strezimir/photo/strezimir_1600x1200_now.jpg
  :interval: 120
  :desc: karkonosze_strezimir
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/polesi/photo/polesi_now.jpg
  :interval: 140
  :desc: karkonosze_polesi
  :use_in_timelapse: false

- :url: http://kamery.hydronet.cz/brod/photo/brod_1600x1200_now.jpg
  :interval: 150
  :desc: karkonosze_zelazny_brod
  :use_in_timelapse: false

- :url: http://kamery.humlnet.cz/images/webcams/chata_vatra/1600x1200.jpg
  :resize: true
  :jpg_quality_offset: 10
  :interval: 120
  :desc: sudety_chata_vatra
  :lat: 50.9
  :lon: 15.333333
  :use_in_timelapse: false

- :url: http://kamery.humlnet.cz/images/webcams/lucnibouda/1600x1200.jpg
  :resize: true
  :jpg_quality_offset: 10
  :interval: 150
  :desc: lucnibouda
  :lat: 50.9
  :lon: 15.333333
  :use_in_timelapse: false

- :url: http://portal.chmi.cz/files/portal/docs/meteo/kam/lysa_hora3.jpg
  :interval: 120
  :desc: lysa_hora
  :resize: true
  :jpg_quality_offset: 14
  :lat: 49.545833
  :lon: 18.4475
  :use_in_timelapse: false

- :url: http://www.kompas.pl/kamerki/szczniec_widok000M.jpg
  :interval: 110
  :desc: sudety_szczeliniec2
  :lat: 50.9
  :lon: 15.333333
  :use_in_timelapse: false

  # http://kamery.hydronet.cz/vrbata/

- :url: http://www.kompas.pl/kamerki/pstrka_widok000M.jpg
  :interval: 110
  :desc: sudety_szczeliniec1
  :lat: 50.9
  :lon: 15.333333
  :use_in_timelapse: false

- :resize: false
  :url: http://www.tanvald.cz/data/webkamery/tanvald.jpg
  :interval: 120
  :desc: chech_tanvald
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://www.chalupanarozcesti.cz/webcam/video.jpg
  :interval: 120
  :desc: chech_chalupanarozcesti
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/pecpodsnezkou/1024x768.jpg
  :interval: 120
  :desc: chech_pecpodsnezkou
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/gablenz2/1024x768.jpg
  :interval: 120
  :desc: chech_trutnov2
  :coord:
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/litomerice/1024x768.jpg
  :interval: 120
  :desc: chech_litomerice
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/lovos/1024x768.jpg
  :interval: 120
  :desc: chech_lovos
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/cerna_hora/1024x768.jpg
  :interval: 120
  :desc: chech_cerna_hora
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/labska_bouda/1024x768.jpg
  :interval: 120
  :desc: chech_labska_bouda
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/boudapodsnezkou/1024x768.jpg
  :interval: 120
  :desc: chech_boudapodsnezkou
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/prkenak/1024x768.jpg
  :interval: 120
  :desc: chech_prkenak
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://kamery.humlnet.cz/images/webcams/boruvka/1024x768.jpg
  :interval: 120
  :desc: chech_velka_upa_boruvka
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://bartanet.cz/~foto/kamera/spindlerovka.jpg
  :interval: 240
  :desc: chech_spindlerovka2
  :use_in_timelapse: false

- :resize: false
  :url: http://www.kamera.karpacz.pl/lodowiec.jpg
  :interval: 120
  :desc: karpacz_garb
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://webcam.box3.pl/new_file.php?camera=plac2
  :interval: 180
  :desc: poland_jelenia_cieplice
  :use_in_timelapse: false

- :resize: false
  :url: http://webcam.box3.pl/new_file.php?camera=zachelmie
  :interval: 180
  :desc: poland_jelenia_zachelmie
  :use_in_timelapse: false

- :resize: false
  :url: http://www.infoo.net/sniezka_karpacz.jpg
  :interval: 180
  :desc: poland_karpacz_sniezka
  :use_in_timelapse: false

- :resize: true
  :jpg_quality_offset: 5
  :url: http://kamery.humlnet.cz/images/webcams/snezka3/2048x1536.jpg
  :interval: 3600
  :desc: sniezka0
  :lat: 50.735833
  :lon: 15.739167
  :use_in_timelapse: false

- :resize: true
  :jpg_quality_offset: 5
  :url: http://kamery.humlnet.cz/images/webcams/snezka2/2048x1536.jpg
  :interval: 160
  :desc: sniezka1
  :lat: 50.735833
  :lon: 15.739167
  # foggy
  :use_in_timelapse: false

- :resize: true
  :jpg_quality_offset: 5
  :url: http://kamery.humlnet.cz/images/webcams/snezka/2048x1536.jpg
  :interval: 160
  :desc: sniezka2
  :lat: 50.735833
  :lon: 15.739167
  # foggy
  :use_in_timelapse: false

- :resize: false
  :url: http://www.karpacz.eu/cam_pliki/cam2.php
  :interval: 120
  :desc: karpacz2
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :resize: false
  :url: http://sokolowsko.pl/soko-cam.jpg
  :interval: 150
  :desc: sokolowsko
  :lat: 50.288333
  :lon: 18.973611
  :use_in_timelapse: false

- :interval: 120
  :desc: karpacz_3_maja
  :url: http://www.karpacz.eu/camera.php
  :resize: false
  :use_in_timelapse: false

- :interval: 60
  :desc: kowary_deptak
  :url: http://www.kowary.pl/kamera/obrazek002.jpg
  :resize: true
  :jpg_quality_offset: -5
  :use_in_timelapse: false
